version: '3.7'
 
services:

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: qwerty123
      
    # volumes:
    #   - ./3-DATOS/mssql/Data/:/var/opt/mssql